# Generated by Django 5.2 on 2025-04-15 13:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitor',
            name='canvas_fp',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='visitor',
            name='fonts_fp',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='visitor',
            name='webgl_fp',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.CreateModel(
            name='BehaviorData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_url', models.CharField(max_length=500)),
                ('mouse_movements', models.JSONField(default=list)),
                ('clicks', models.JSONField(default=list)),
                ('scroll_events', models.JSONField(default=list)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('visitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.visitor')),
            ],
        ),
    ]
