# Generated by Django 5.2 on 2025-04-15 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_alter_visitor_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitor',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='visitor',
            name='country',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='visitor',
            name='is_touch_device',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='visitor',
            name='language',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='visitor',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='visitor',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='visitor',
            name='screen_resolution',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='canvas_fp',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='webgl_fp',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
