# Generated by Django 5.2 on 2025-04-15 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_visitor_asn_visitor_audio_fp_visitor_cpu_cores_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visitor',
            name='asn',
        ),
        migrations.RemoveField(
            model_name='visitor',
            name='fonts_fp',
        ),
        migrations.RemoveField(
            model_name='visitor',
            name='isp',
        ),
        migrations.RemoveField(
            model_name='visitor',
            name='timezone',
        ),
        migrations.RemoveField(
            model_name='visitor',
            name='webrtc_support',
        ),
        migrations.AlterField(
            model_name='visitor',
            name='region',
            field=models.CharField(blank=True, default=1, max_length=100),
            preserve_default=False,
        ),
    ]
